adi:
  frontend-url: http://localhost:1002
  backend-url: http://localhost:1002/api
  proxy:
    enable: true
    host: 127.0.0.1
    http-port: 7890
  # embedding model可选值如下（见adi_ai_model中的embedding类型的数据）：
  # local:all-minilm-l6-v2 (英文效果较好，中文效果较差)
  # local:bge-small-zh-v1.5 (默认、中文效果较好、相比 all-minilm-l6-v2 占用内存较大)
  # openai:text-embedding-3-small、openai:text-embedding-3-large (多语言)
  # dashscope:text-embedding-v1、dashscope:text-embedding-v3  (多语言，中文效果较好)
  # 注意：由于不同向量模型不同维度参数生成的向量特征空间不一致，无法兼容存储于一张表并进行混合搜索，建议项目初期确定好向量模型及其维度，后期如有修改，需重新生成向量数据
  embedding-model: local:bge-small-zh-v1.5
  # vector-database: pgvector、neo4j
  vector-database: neo4j
  # graph-database: apache-age、neo4j
  graph-database: neo4j
  datasource:
    neo4j:
      host: 10.30.3.93
      port: 7987
      username: neo4j
      password: 123!@#qwe
      database: neo4j